-- ================================================================
-- InvestMentor AI – AI-Driven Personal Investment Strategy Assistant (Educational Only)
-- Stage 1-5 consolidated deployment script
-- Assumptions: executed by application owner schema with APEX installed.
-- Disclaimer constant reused throughout outputs.
-- ================================================================

PROMPT === STAGE 1: DDL ===

-- Global disclaimer table for reuse
CREATE TABLE disclaimers (
    disclaimer_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    code             VARCHAR2(50) UNIQUE NOT NULL,
    text             CLOB NOT NULL,
    active_flag      CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y','N')),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX(disclaimers(code)) */ INTO disclaimers(code,text)
VALUES ('GLOBAL_EDU','This advice is for educational purposes only. No information provided constitutes financial advice, and no return on investment is guaranteed.');

-- === USER & CONSENT ===
CREATE TABLE users (
    user_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    external_user_ref VARCHAR2(100) UNIQUE,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    status           VARCHAR2(20) DEFAULT 'ACTIVE'
);

CREATE TABLE user_demographics (
    user_id          NUMBER PRIMARY KEY REFERENCES users(user_id),
    age              NUMBER,
    country          VARCHAR2(100),
    marital_status   VARCHAR2(30),
    jurisdiction     VARCHAR2(100),
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE user_consent (
    consent_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    consent_type     VARCHAR2(50) NOT NULL,
    version_code     VARCHAR2(30) NOT NULL,
    accepted_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    channel          VARCHAR2(30),
    disclaimer_id    NUMBER REFERENCES disclaimers(disclaimer_id)
);

-- === RISK QUESTIONNAIRE ===
CREATE TABLE risk_questionnaires (
    questionnaire_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name             VARCHAR2(200) NOT NULL,
    version_no       NUMBER NOT NULL,
    effective_from   DATE DEFAULT SYSDATE,
    effective_to     DATE,
    status           VARCHAR2(20) DEFAULT 'ACTIVE'
);

CREATE TABLE risk_questions (
    question_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    questionnaire_id NUMBER NOT NULL REFERENCES risk_questionnaires(questionnaire_id),
    prompt           VARCHAR2(500) NOT NULL,
    display_order    NUMBER,
    mandatory_flag   CHAR(1) DEFAULT 'Y' CHECK (mandatory_flag IN ('Y','N'))
);

CREATE TABLE risk_options (
    option_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    question_id      NUMBER NOT NULL REFERENCES risk_questions(question_id),
    option_text      VARCHAR2(400) NOT NULL,
    score_value      NUMBER NOT NULL,
    display_order    NUMBER
);

CREATE TABLE risk_responses (
    response_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    questionnaire_id NUMBER NOT NULL REFERENCES risk_questionnaires(questionnaire_id),
    question_id      NUMBER NOT NULL REFERENCES risk_questions(question_id),
    option_id        NUMBER NOT NULL REFERENCES risk_options(option_id),
    responded_at     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE risk_categories (
    category_code    VARCHAR2(30) PRIMARY KEY,
    label            VARCHAR2(100),
    min_score        NUMBER,
    max_score        NUMBER
);

CREATE TABLE risk_profile_results (
    result_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    questionnaire_id NUMBER NOT NULL REFERENCES risk_questionnaires(questionnaire_id),
    total_score      NUMBER,
    category_code    VARCHAR2(30) REFERENCES risk_categories(category_code),
    calculated_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- === FINANCIAL POSITION ===
CREATE TABLE asset_types (
    asset_type_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    code             VARCHAR2(50) UNIQUE,
    description      VARCHAR2(200),
    class_group      VARCHAR2(50)
);

CREATE TABLE liability_types (
    liability_type_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    code              VARCHAR2(50) UNIQUE,
    description       VARCHAR2(200)
);

CREATE TABLE user_assets (
    asset_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    asset_type_id    NUMBER NOT NULL REFERENCES asset_types(asset_type_id),
    current_value    NUMBER(18,2) DEFAULT 0,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE user_liabilities (
    liability_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    liability_type_id NUMBER NOT NULL REFERENCES liability_types(liability_type_id),
    outstanding_amt  NUMBER(18,2) DEFAULT 0,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE user_income (
    income_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    income_source    VARCHAR2(200),
    monthly_amount   NUMBER(18,2),
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE user_expenses (
    expense_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    expense_band     VARCHAR2(100),
    monthly_amount   NUMBER(18,2),
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- === GOALS & PROGRESS ===
CREATE TABLE goal_types (
    goal_type_code   VARCHAR2(30) PRIMARY KEY,
    description      VARCHAR2(200)
);

CREATE TABLE user_goals (
    goal_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    goal_type_code   VARCHAR2(30) REFERENCES goal_types(goal_type_code),
    target_amount    NUMBER(18,2),
    current_savings  NUMBER(18,2),
    target_date      DATE,
    priority_rank    NUMBER,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE goal_progress (
    progress_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    goal_id          NUMBER NOT NULL REFERENCES user_goals(goal_id),
    funding_gap      NUMBER(18,2),
    status_code      VARCHAR2(20),
    calculated_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- === STRATEGY & SCENARIOS ===
CREATE TABLE risk_strategy_templates (
    template_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category_code    VARCHAR2(30) REFERENCES risk_categories(category_code),
    horizon_band     VARCHAR2(50),
    equity_pct_min   NUMBER CHECK (equity_pct_min BETWEEN 0 AND 100),
    equity_pct_max   NUMBER CHECK (equity_pct_max BETWEEN 0 AND 100),
    bond_pct_min     NUMBER CHECK (bond_pct_min BETWEEN 0 AND 100),
    bond_pct_max     NUMBER CHECK (bond_pct_max BETWEEN 0 AND 100),
    cash_pct_min     NUMBER CHECK (cash_pct_min BETWEEN 0 AND 100),
    cash_pct_max     NUMBER CHECK (cash_pct_max BETWEEN 0 AND 100),
    alternatives_pct NUMBER CHECK (alternatives_pct BETWEEN 0 AND 100)
);

CREATE TABLE scenarios (
    scenario_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    goal_id          NUMBER REFERENCES user_goals(goal_id),
    scenario_name    VARCHAR2(200),
    horizon_years    NUMBER,
    base_contribution NUMBER(18,2),
    allocation_label VARCHAR2(100),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE scenario_parameters (
    param_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    scenario_id      NUMBER NOT NULL REFERENCES scenarios(scenario_id),
    param_name       VARCHAR2(100),
    param_value      VARCHAR2(200)
);

CREATE TABLE scenario_results (
    result_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    scenario_id      NUMBER NOT NULL REFERENCES scenarios(scenario_id),
    projected_value  NUMBER(18,2),
    total_contrib    NUMBER(18,2),
    rule_version     VARCHAR2(50),
    disclaimer_id    NUMBER REFERENCES disclaimers(disclaimer_id),
    generated_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    notes            VARCHAR2(4000)
);

-- === CONTENT LIBRARY ===
CREATE TABLE content_items (
    content_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title            VARCHAR2(200),
    body             CLOB,
    level_code       VARCHAR2(30),
    topic            VARCHAR2(100),
    persona_hint     VARCHAR2(100)
);

CREATE TABLE content_tags (
    tag_code         VARCHAR2(50) PRIMARY KEY,
    description      VARCHAR2(200)
);

CREATE TABLE content_item_tags (
    content_id       NUMBER REFERENCES content_items(content_id),
    tag_code         VARCHAR2(50) REFERENCES content_tags(tag_code),
    PRIMARY KEY (content_id, tag_code)
);

-- === SESSION & CONVERSATION LOG ===
CREATE TABLE sessions (
    session_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL REFERENCES users(user_id),
    started_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    ended_at         TIMESTAMP,
    channel          VARCHAR2(30),
    persona_label    VARCHAR2(50)
);

CREATE TABLE session_messages (
    message_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    session_id       NUMBER NOT NULL REFERENCES sessions(session_id),
    direction        VARCHAR2(10) CHECK (direction IN ('USER','SYSTEM')),
    message_type     VARCHAR2(50),
    message_text     CLOB,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- === ADMIN & CONFIG ===
CREATE TABLE config_parameters (
    param_name       VARCHAR2(100) PRIMARY KEY,
    param_value      VARCHAR2(4000),
    description      VARCHAR2(400)
);

CREATE TABLE rule_sets (
    rule_set_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name             VARCHAR2(200),
    description      VARCHAR2(400)
);

CREATE TABLE rule_versions (
    rule_version_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    rule_set_id      NUMBER REFERENCES rule_sets(rule_set_id),
    version_code     VARCHAR2(50),
    effective_from   DATE DEFAULT SYSDATE,
    effective_to     DATE
);

-- === AUDIT & LOGGING ===
CREATE TABLE audit_events (
    audit_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id          NUMBER,
    event_type       VARCHAR2(50),
    event_detail     VARCHAR2(4000),
    occurred_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE admin_change_log (
    change_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    changed_object   VARCHAR2(100),
    change_detail    VARCHAR2(4000),
    changed_by       VARCHAR2(100),
    changed_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

PROMPT === STAGE 2: PL/SQL PACKAGES ===

-- Utility function for disclaimer text
CREATE OR REPLACE PACKAGE pkg_constants AS
    c_global_disclaimer CONSTANT VARCHAR2(500) := 'This advice is for educational purposes only. No information provided constitutes financial advice, and no return on investment is guaranteed.';
END pkg_constants;
/

CREATE OR REPLACE PACKAGE pkg_user_mgmt AS
    PROCEDURE create_user(p_external_ref IN VARCHAR2, p_user_id OUT NUMBER);
    PROCEDURE upsert_demographics(p_user_id IN NUMBER, p_age IN NUMBER, p_country IN VARCHAR2, p_marital IN VARCHAR2, p_jurisdiction IN VARCHAR2);
    PROCEDURE record_consent(p_user_id IN NUMBER, p_type IN VARCHAR2, p_version IN VARCHAR2, p_channel IN VARCHAR2);
END pkg_user_mgmt;
/
CREATE OR REPLACE PACKAGE BODY pkg_user_mgmt AS
    PROCEDURE create_user(p_external_ref IN VARCHAR2, p_user_id OUT NUMBER) IS
    BEGIN
        INSERT INTO users(external_user_ref) VALUES (p_external_ref) RETURNING user_id INTO p_user_id;
    END;
    PROCEDURE upsert_demographics(p_user_id IN NUMBER, p_age IN NUMBER, p_country IN VARCHAR2, p_marital IN VARCHAR2, p_jurisdiction IN VARCHAR2) IS
    BEGIN
        MERGE INTO user_demographics d USING (SELECT p_user_id user_id FROM dual) s
        ON (d.user_id = s.user_id)
        WHEN MATCHED THEN UPDATE SET age=p_age, country=p_country, marital_status=p_marital, jurisdiction=p_jurisdiction, updated_at=SYSTIMESTAMP
        WHEN NOT MATCHED THEN INSERT(user_id, age, country, marital_status, jurisdiction) VALUES (p_user_id, p_age, p_country, p_marital, p_jurisdiction);
    END;
    PROCEDURE record_consent(p_user_id IN NUMBER, p_type IN VARCHAR2, p_version IN VARCHAR2, p_channel IN VARCHAR2) IS
        l_disc_id NUMBER;
    BEGIN
        SELECT disclaimer_id INTO l_disc_id FROM disclaimers WHERE code='GLOBAL_EDU' AND active_flag='Y' FETCH FIRST 1 ROWS ONLY;
        INSERT INTO user_consent(user_id, consent_type, version_code, channel, disclaimer_id) VALUES (p_user_id, p_type, p_version, p_channel, l_disc_id);
    END;
END pkg_user_mgmt;
/

CREATE OR REPLACE PACKAGE pkg_risk_profile AS
    FUNCTION compute_score(p_user_id IN NUMBER, p_questionnaire_id IN NUMBER) RETURN NUMBER;
    FUNCTION derive_category(p_score IN NUMBER) RETURN VARCHAR2;
    PROCEDURE save_result(p_user_id IN NUMBER, p_questionnaire_id IN NUMBER);
END pkg_risk_profile;
/
CREATE OR REPLACE PACKAGE BODY pkg_risk_profile AS
    FUNCTION compute_score(p_user_id IN NUMBER, p_questionnaire_id IN NUMBER) RETURN NUMBER IS
        l_score NUMBER;
    BEGIN
        SELECT NVL(SUM(o.score_value),0)
        INTO l_score
        FROM risk_responses r
        JOIN risk_options o ON r.option_id=o.option_id
        WHERE r.user_id=p_user_id AND r.questionnaire_id=p_questionnaire_id;
        RETURN l_score;
    END;
    FUNCTION derive_category(p_score IN NUMBER) RETURN VARCHAR2 IS
        l_cat VARCHAR2(30);
    BEGIN
        SELECT category_code INTO l_cat FROM risk_categories WHERE p_score BETWEEN NVL(min_score,0) AND NVL(max_score,99999) FETCH FIRST 1 ROWS ONLY;
        RETURN l_cat;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 'UNCLASSIFIED';
    END;
    PROCEDURE save_result(p_user_id IN NUMBER, p_questionnaire_id IN NUMBER) IS
        l_score NUMBER;
        l_cat VARCHAR2(30);
    BEGIN
        l_score := compute_score(p_user_id, p_questionnaire_id);
        l_cat := derive_category(l_score);
        INSERT INTO risk_profile_results(user_id, questionnaire_id, total_score, category_code) VALUES (p_user_id, p_questionnaire_id, l_score, l_cat);
    END;
END pkg_risk_profile;
/

CREATE OR REPLACE PACKAGE pkg_financial_snapshot AS
    FUNCTION net_worth(p_user_id IN NUMBER) RETURN NUMBER;
    FUNCTION allocation_summary(p_user_id IN NUMBER) RETURN SYS_REFCURSOR;
END pkg_financial_snapshot;
/
CREATE OR REPLACE PACKAGE BODY pkg_financial_snapshot AS
    FUNCTION net_worth(p_user_id IN NUMBER) RETURN NUMBER IS
        l_assets NUMBER; l_liabs NUMBER;
    BEGIN
        SELECT NVL(SUM(current_value),0) INTO l_assets FROM user_assets WHERE user_id=p_user_id;
        SELECT NVL(SUM(outstanding_amt),0) INTO l_liabs FROM user_liabilities WHERE user_id=p_user_id;
        RETURN l_assets - l_liabs;
    END;
    FUNCTION allocation_summary(p_user_id IN NUMBER) RETURN SYS_REFCURSOR IS
        l_rc SYS_REFCURSOR;
    BEGIN
        OPEN l_rc FOR
        SELECT at.class_group, SUM(ua.current_value) total_value
        FROM user_assets ua JOIN asset_types at ON ua.asset_type_id=at.asset_type_id
        WHERE ua.user_id=p_user_id
        GROUP BY at.class_group;
        RETURN l_rc;
    END;
END pkg_financial_snapshot;
/

CREATE OR REPLACE PACKAGE pkg_goals AS
    PROCEDURE upsert_goal(p_user_id IN NUMBER, p_goal_id IN OUT NUMBER, p_type IN VARCHAR2, p_target_amt IN NUMBER, p_current IN NUMBER, p_date IN DATE, p_priority IN NUMBER);
    PROCEDURE refresh_progress(p_goal_id IN NUMBER);
END pkg_goals;
/
CREATE OR REPLACE PACKAGE BODY pkg_goals AS
    PROCEDURE upsert_goal(p_user_id IN NUMBER, p_goal_id IN OUT NUMBER, p_type IN VARCHAR2, p_target_amt IN NUMBER, p_current IN NUMBER, p_date IN DATE, p_priority IN NUMBER) IS
    BEGIN
        IF p_goal_id IS NULL THEN
            INSERT INTO user_goals(user_id, goal_type_code, target_amount, current_savings, target_date, priority_rank)
            VALUES (p_user_id, p_type, p_target_amt, p_current, p_date, p_priority) RETURNING goal_id INTO p_goal_id;
        ELSE
            UPDATE user_goals SET goal_type_code=p_type, target_amount=p_target_amt, current_savings=p_current, target_date=p_date, priority_rank=p_priority WHERE goal_id=p_goal_id;
        END IF;
        refresh_progress(p_goal_id);
    END;
    PROCEDURE refresh_progress(p_goal_id IN NUMBER) IS
        l_gap NUMBER; l_status VARCHAR2(20);
    BEGIN
        SELECT target_amount - current_savings INTO l_gap FROM user_goals WHERE goal_id=p_goal_id;
        IF l_gap <= 0 THEN l_status := 'on-track';
        ELSIF l_gap <= (SELECT TO_NUMBER(param_value) FROM config_parameters WHERE param_name='GOAL_SLACK' FETCH FIRST 1 ROWS ONLY) THEN l_status := 'slightly-behind';
        ELSE l_status := 'at-risk';
        END IF;
        INSERT INTO goal_progress(goal_id, funding_gap, status_code) VALUES (p_goal_id, l_gap, l_status);
    END;
END pkg_goals;
/

CREATE OR REPLACE PACKAGE pkg_scenario_engine AS
    PROCEDURE create_scenario(p_user_id IN NUMBER, p_goal_id IN NUMBER, p_name IN VARCHAR2, p_horizon_years IN NUMBER, p_contrib IN NUMBER, p_alloc_label IN VARCHAR2, p_scenario_id OUT NUMBER);
    PROCEDURE run_projection(p_scenario_id IN NUMBER, p_rate IN NUMBER DEFAULT 0.05);
END pkg_scenario_engine;
/
CREATE OR REPLACE PACKAGE BODY pkg_scenario_engine AS
    PROCEDURE create_scenario(p_user_id IN NUMBER, p_goal_id IN NUMBER, p_name IN VARCHAR2, p_horizon_years IN NUMBER, p_contrib IN NUMBER, p_alloc_label IN VARCHAR2, p_scenario_id OUT NUMBER) IS
    BEGIN
        INSERT INTO scenarios(user_id, goal_id, scenario_name, horizon_years, base_contribution, allocation_label)
        VALUES (p_user_id, p_goal_id, p_name, p_horizon_years, p_contrib, p_alloc_label)
        RETURNING scenario_id INTO p_scenario_id;
    END;
    PROCEDURE run_projection(p_scenario_id IN NUMBER, p_rate IN NUMBER DEFAULT 0.05) IS
        l_years NUMBER; l_contrib NUMBER; l_fv NUMBER; l_total NUMBER; l_disc NUMBER;
    BEGIN
        SELECT horizon_years, base_contribution INTO l_years, l_contrib FROM scenarios WHERE scenario_id=p_scenario_id;
        l_total := l_contrib * 12 * l_years;
        l_fv := l_contrib * 12 * ((POWER(1+p_rate, l_years) - 1) / p_rate);
        SELECT disclaimer_id INTO l_disc FROM disclaimers WHERE code='GLOBAL_EDU' FETCH FIRST 1 ROWS ONLY;
        INSERT INTO scenario_results(scenario_id, projected_value, total_contrib, rule_version, disclaimer_id, notes)
        VALUES (p_scenario_id, l_fv, l_total, 'v1', l_disc, 'Deterministic projection using constant rate; '||pkg_constants.c_global_disclaimer);
    END;
END pkg_scenario_engine;
/

CREATE OR REPLACE PACKAGE pkg_content_library AS
    FUNCTION search_content(p_level IN VARCHAR2, p_topic IN VARCHAR2) RETURN SYS_REFCURSOR;
END pkg_content_library;
/
CREATE OR REPLACE PACKAGE BODY pkg_content_library AS
    FUNCTION search_content(p_level IN VARCHAR2, p_topic IN VARCHAR2) RETURN SYS_REFCURSOR IS
        l_rc SYS_REFCURSOR;
    BEGIN
        OPEN l_rc FOR SELECT * FROM content_items WHERE level_code=NVL(p_level, level_code) AND topic LIKE NVL(p_topic, topic);
        RETURN l_rc;
    END;
END pkg_content_library;
/

CREATE OR REPLACE PACKAGE pkg_session_log AS
    PROCEDURE start_session(p_user_id IN NUMBER, p_channel IN VARCHAR2, p_persona IN VARCHAR2, p_session_id OUT NUMBER);
    PROCEDURE end_session(p_session_id IN NUMBER);
    PROCEDURE log_message(p_session_id IN NUMBER, p_direction IN VARCHAR2, p_type IN VARCHAR2, p_text IN CLOB);
END pkg_session_log;
/
CREATE OR REPLACE PACKAGE BODY pkg_session_log AS
    PROCEDURE start_session(p_user_id IN NUMBER, p_channel IN VARCHAR2, p_persona IN VARCHAR2, p_session_id OUT NUMBER) IS
    BEGIN
        INSERT INTO sessions(user_id, channel, persona_label) VALUES (p_user_id, p_channel, p_persona) RETURNING session_id INTO p_session_id;
    END;
    PROCEDURE end_session(p_session_id IN NUMBER) IS
    BEGIN
        UPDATE sessions SET ended_at=SYSTIMESTAMP WHERE session_id=p_session_id;
    END;
    PROCEDURE log_message(p_session_id IN NUMBER, p_direction IN VARCHAR2, p_type IN VARCHAR2, p_text IN CLOB) IS
    BEGIN
        INSERT INTO session_messages(session_id, direction, message_type, message_text) VALUES (p_session_id, p_direction, p_type, p_text || CHR(10)|| pkg_constants.c_global_disclaimer);
    END;
END pkg_session_log;
/

CREATE OR REPLACE PACKAGE pkg_advisor_view AS
    FUNCTION advisor_summary(p_user_id IN NUMBER) RETURN CLOB;
END pkg_advisor_view;
/
CREATE OR REPLACE PACKAGE BODY pkg_advisor_view AS
    FUNCTION advisor_summary(p_user_id IN NUMBER) RETURN CLOB IS
        l_summary CLOB;
        l_net NUMBER;
    BEGIN
        l_net := pkg_financial_snapshot.net_worth(p_user_id);
        l_summary := 'Client net worth (approx): '||l_net||'. Goals and scenarios stored for compliance. '||pkg_constants.c_global_disclaimer;
        RETURN l_summary;
    END;
END pkg_advisor_view;
/

CREATE OR REPLACE PACKAGE pkg_admin_config AS
    PROCEDURE set_param(p_name IN VARCHAR2, p_value IN VARCHAR2, p_desc IN VARCHAR2 := NULL, p_user IN VARCHAR2 := USER);
END pkg_admin_config;
/
CREATE OR REPLACE PACKAGE BODY pkg_admin_config AS
    PROCEDURE set_param(p_name IN VARCHAR2, p_value IN VARCHAR2, p_desc IN VARCHAR2, p_user IN VARCHAR2) IS
    BEGIN
        MERGE INTO config_parameters c USING (SELECT p_name name FROM dual) s ON (c.param_name=s.name)
        WHEN MATCHED THEN UPDATE SET param_value=p_value, description=NVL(p_desc, description)
        WHEN NOT MATCHED THEN INSERT(param_name, param_value, description) VALUES (p_name, p_value, p_desc);
        INSERT INTO admin_change_log(changed_object, change_detail, changed_by) VALUES ('CONFIG_PARAM', p_name||'='||p_value, p_user);
    END;
END pkg_admin_config;
/

CREATE OR REPLACE PACKAGE pkg_audit AS
    PROCEDURE log_event(p_user_id IN NUMBER, p_type IN VARCHAR2, p_detail IN VARCHAR2);
END pkg_audit;
/
CREATE OR REPLACE PACKAGE BODY pkg_audit AS
    PROCEDURE log_event(p_user_id IN NUMBER, p_type IN VARCHAR2, p_detail IN VARCHAR2) IS
    BEGIN
        INSERT INTO audit_events(user_id, event_type, event_detail) VALUES (p_user_id, p_type, p_detail);
    END;
END pkg_audit;
/

CREATE OR REPLACE PACKAGE pkg_ai_stub AS
    PROCEDURE call_llm_stub(p_prompt IN CLOB, p_response OUT CLOB);
END pkg_ai_stub;
/
CREATE OR REPLACE PACKAGE BODY pkg_ai_stub AS
    PROCEDURE call_llm_stub(p_prompt IN CLOB, p_response OUT CLOB) IS
    BEGIN
        p_response := 'Educational explanation based on your prompt: '||SUBSTR(p_prompt,1,200)||' ... '||pkg_constants.c_global_disclaimer;
    END;
END pkg_ai_stub;
/

PROMPT === STAGE 3: SEED DATA ===

BEGIN
    INSERT INTO risk_categories(category_code,label,min_score,max_score) VALUES('CONSERVATIVE','Conservative',0,20);
    INSERT INTO risk_categories(category_code,label,min_score,max_score) VALUES('MODERATE','Moderate',21,40);
    INSERT INTO risk_categories(category_code,label,min_score,max_score) VALUES('BALANCED','Balanced',41,60);
    INSERT INTO risk_categories(category_code,label,min_score,max_score) VALUES('GROWTH','Growth',61,80);
    INSERT INTO risk_categories(category_code,label,min_score,max_score) VALUES('AGGRESSIVE','Aggressive',81,120);
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

BEGIN
    INSERT INTO goal_types(goal_type_code, description) VALUES ('RETIREMENT','Retirement planning');
    INSERT INTO goal_types(goal_type_code, description) VALUES ('HOME','Home purchase');
    INSERT INTO goal_types(goal_type_code, description) VALUES ('EDU','Education');
    INSERT INTO goal_types(goal_type_code, description) VALUES ('WEALTH','Wealth accumulation');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

BEGIN
    INSERT INTO asset_types(code, description, class_group) VALUES ('CASH','Cash and equivalents','Cash');
    INSERT INTO asset_types(code, description, class_group) VALUES ('EQUITY','Listed equities','Equity');
    INSERT INTO asset_types(code, description, class_group) VALUES ('BOND','Bonds and fixed income','FixedIncome');
    INSERT INTO asset_types(code, description, class_group) VALUES ('ALTS','Alternatives','Alternatives');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

BEGIN
    INSERT INTO liability_types(code, description) VALUES('MORTGAGE','Mortgage loans');
    INSERT INTO liability_types(code, description) VALUES('CONSUMER','Consumer debt');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

BEGIN
    INSERT INTO config_parameters(param_name,param_value,description) VALUES ('GOAL_SLACK','5000','Slack before marking goal at risk');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- Questionnaire seed
DECLARE
    qid NUMBER;
    q1 NUMBER; q2 NUMBER;
BEGIN
    INSERT INTO risk_questionnaires(name, version_no) VALUES ('Default risk survey',1) RETURNING questionnaire_id INTO qid;
    INSERT INTO risk_questions(questionnaire_id, prompt, display_order) VALUES (qid,'How do you feel about short-term losses?',1) RETURNING question_id INTO q1;
    INSERT INTO risk_questions(questionnaire_id, prompt, display_order) VALUES (qid,'Investment horizon?',2) RETURNING question_id INTO q2;
    INSERT INTO risk_options(question_id, option_text, score_value, display_order) VALUES (q1,'I avoid any loss',5,1);
    INSERT INTO risk_options(question_id, option_text, score_value, display_order) VALUES (q1,'Accept small dips',15,2);
    INSERT INTO risk_options(question_id, option_text, score_value, display_order) VALUES (q1,'Comfortable with volatility',30,3);
    INSERT INTO risk_options(question_id, option_text, score_value, display_order) VALUES (q2,'< 3 years',5,1);
    INSERT INTO risk_options(question_id, option_text, score_value, display_order) VALUES (q2,'3-7 years',15,2);
    INSERT INTO risk_options(question_id, option_text, score_value, display_order) VALUES (q2,'> 7 years',30,3);
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Demo user and data
DECLARE
    u NUMBER; g NUMBER; s NUMBER;
BEGIN
    pkg_user_mgmt.create_user('demo_user', u);
    pkg_user_mgmt.upsert_demographics(u,30,'USA','Single','US');
    pkg_user_mgmt.record_consent(u,'AI_EDU','v1','WEB');
    INSERT INTO user_assets(user_id, asset_type_id, current_value) SELECT u, asset_type_id, 20000 FROM asset_types WHERE code='CASH';
    INSERT INTO user_assets(user_id, asset_type_id, current_value) SELECT u, asset_type_id, 40000 FROM asset_types WHERE code='EQUITY';
    INSERT INTO user_liabilities(user_id, liability_type_id, outstanding_amt) SELECT u, liability_type_id, 15000 FROM liability_types WHERE code='MORTGAGE';
    pkg_goals.upsert_goal(u, g, 'RETIREMENT', 300000, 10000, ADD_MONTHS(SYSDATE, 12*25), 1);
    INSERT INTO risk_responses(user_id, questionnaire_id, question_id, option_id)
    SELECT u, rq.questionnaire_id, q.question_id, o.option_id
    FROM risk_questionnaires rq
    JOIN risk_questions q ON q.questionnaire_id = rq.questionnaire_id
    JOIN risk_options o ON o.question_id = q.question_id
    WHERE rq.name='Default risk survey' AND rq.version_no=1 AND o.display_order=2; -- mid risk answers
    pkg_risk_profile.save_result(u, (SELECT questionnaire_id FROM risk_questionnaires WHERE name='Default risk survey' AND version_no=1));
    pkg_scenario_engine.create_scenario(u, g, 'Base case', 25, 200, 'Balanced', s);
    pkg_scenario_engine.run_projection(s);
END;
/

PROMPT === STAGE 4: APEX APPLICATION EXPORT (MINIMAL SHELL) ===

-- Minimal APEX app placeholder using application id 100.
BEGIN
    apex_application_install.set_application_id(100);
    apex_application_install.set_application_name('InvestMentor AI');
    apex_application_install.set_schema(USER);
    apex_application_install.generate_offset;
END;
/

-- Create application shell
BEGIN
    wwv_flow_api.create_flow(p_id=>apex_application_install.get_application_id,
        p_display_id=>apex_application_install.get_application_id,
        p_owner=>USER,
        p_name=>'InvestMentor AI',
        p_alias=>'INVESTMENTOR',
        p_page_view_logging=>'YES',
        p_flow_language=>'en');

    -- Landing Page
    wwv_flow_api.create_page(p_flow_id=>apex_application_install.get_application_id,
        p_page_id=>1, p_name=>'Welcome', p_step_title=>'InvestMentor AI', p_autocomplete_on_off=>'ON');
    wwv_flow_api.create_page_item(p_flow_id=>apex_application_install.get_application_id,
        p_page_id=>1, p_item_name=>'P1_DISCLAIMER', p_item_sequence=>10, p_prompt=>'Disclaimer', p_item_default=>pkg_constants.c_global_disclaimer, p_display_as=>'NATIVE_DISPLAY_ONLY');

    -- Dashboard page stub
    wwv_flow_api.create_page(p_flow_id=>apex_application_install.get_application_id, p_page_id=>2, p_name=>'Dashboard', p_step_title=>'Dashboard');
    wwv_flow_api.create_page_item(p_flow_id=>apex_application_install.get_application_id, p_page_id=>2, p_item_name=>'P2_NETWORTH', p_prompt=>'Net Worth', p_source_type=>'FUNCTION_BODY',
        p_item_source=> 'return pkg_financial_snapshot.net_worth(:APP_USER_ID);');

    -- Scenario form stub
    wwv_flow_api.create_page(p_flow_id=>apex_application_install.get_application_id, p_page_id=>3, p_name=>'Scenario', p_step_title=>'Scenario');
    wwv_flow_api.create_page_item(p_flow_id=>apex_application_install.get_application_id, p_page_id=>3, p_item_name=>'P3_NAME', p_prompt=>'Scenario Name', p_display_as=>'NATIVE_TEXT_FIELD');
    wwv_flow_api.create_page_item(p_flow_id=>apex_application_install.get_application_id, p_page_id=>3, p_item_name=>'P3_YEARS', p_prompt=>'Horizon (years)', p_display_as=>'NATIVE_NUMBER_FIELD');
    wwv_flow_api.create_page_item(p_flow_id=>apex_application_install.get_application_id, p_page_id=>3, p_item_name=>'P3_CONTRIB', p_prompt=>'Monthly Contribution', p_display_as=>'NATIVE_NUMBER_FIELD');

    -- Conversation log report stub
    wwv_flow_api.create_page(p_flow_id=>apex_application_install.get_application_id, p_page_id=>4, p_name=>'Conversation', p_step_title=>'Conversation');

END;
/

PROMPT === STAGE 5: DEPLOYMENT GUIDE ===
-- Steps:
-- 1. Connect as application owner schema.
-- 2. Run this script in SQL*Plus/SQLcl to create tables, packages, and seed data.
-- 3. Import the APEX application by running Stage 4 block in an APEX-enabled schema.
-- 4. Configure authentication and map roles END_USER, ADVISOR, ADMIN, COMPLIANCE via APEX authorization schemes.
-- 5. Adjust configuration parameters using pkg_admin_config.set_param.
-- 6. Verify disclaimer text in disclaimers table and UI items.
